### ISSUE TITLE
PSG HiHat problem

### ISSUE THREAD

**Issue by bca759577** [AidanHockey5/Teensy_3_5_VGM_Player_YM2612_SN76489#3] opened 2018-09-26 13:31 UTC
Some songs I can't hear PSG's hi hat sound
Example: Sonic 3 Data Select
I have to manually touch the D6 pin of the SN76496 to Vcc to achieve the effect.
Why is that?

**Comment by AidanHockey5** [comment] 2018-09-26 18:23
Good question. I actually tried shorting pin 6 of the SN76489 on my newer [Mega Blaster](https://github.com/AidanHockey5/STM32_VGM_Player_YM2612_SN76489) to 3.3v to see what would happen. The result was odd. It seemed to mute the YM2612 and distort the SN76489 a little, but I could hear the hi-hat a bit better. I think what's happening is that the hi-hat is playing correctly, but might be getting drowned out by the YM2612. Some of the filtering circuitry might also be removing the hi-hat sound, but I'll have to experiment a little bit more and find out.

**Comment by bca759577** [comment] 2018-09-27 04:12
I have tried sn76494. Although the pitch is different, hihat is working normally. Its frequency is 500khz.

**Comment by AidanHockey5** [comment] 2018-09-27 04:17
Interesting. Well, if you're using LTC6903's to clock your sound chips, you can change line 469 which looks like this: 
`SetClock(11, 831, SN_CLOCK_CS); //3.58 MHz`

to this:

`SetClock(8, 959, SN_CLOCK_CS); //500KHz`

That should correct your pitch with the SN76494.

**Comment by AidanHockey5** [comment] 2018-09-27 04:26
Actually, now that I think about it, your pitch may still be incorrect at 500 KHz since the original SN76489 is not clocked at its full 4MHz speed, instead, it's around 3.58MHz.
If 500KHz sounds a little too high-pitched, maybe try 447.6KHz.

`SetClock(8, 831, SN_CLOCK_CS); //447.6KHz`

I'm not sure if it will exactly match the SN76489 at 3.58MHz, but I figure that if I changed the SN76494's frequency to be proportional to the SN76489's clock speed, the pitch should be a bit more accurate.

**Comment by bca759577** [comment] 2018-09-28 05:19
I have an idea. Can I transfer real data from the computer simulator (ex.KEGA Fusion) to these chips? This must be great.

**Comment by AidanHockey5** [comment] 2018-09-29 19:41
The code as it is now is not designed to handle commands over serial, so you would have to program an interface for that yourself. That is outside the scope of this issue though, so for now, I am closing it.

For future reference, this project was designed for the SN76489 in mind, not the SN76494 since those chips operate at two difference clock speeds.

**Closed as completed by AidanHockey5** 2018-09-29 19:41 UTC
